import { writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const now = new Date().toISOString()

function dl(nodeId, i, speaker, text, emotion) {
  return { id: `dl_${nodeId}_${String(i).padStart(2,'0')}`, speaker, text, emotion }
}
function ch(nodeId, i, text, target, conditions='', effects='', weight='light') {
  return { id: `ch_${nodeId}_${i}`, nodeId, text, order: i, targetNodeId: target, conditions, variableEffects: effects, consequence: '', choiceWeight: weight }
}

const chapters = [
  { id: 'ch1', title: '敲门声', order: 0 },
  { id: 'ch2', title: '卷宗', order: 1 },
  { id: 'ch3', title: '判决', order: 2 },
]

const acts = [
  { id: 'act1', chapterId: 'ch1', title: '引子', order: 0, nodeIds: ['n01','n02'], dramaticFunction: 'setup' },
  { id: 'act2', chapterId: 'ch1', title: '接触', order: 1, nodeIds: ['n03a','n04a','n03b','n04b'], dramaticFunction: 'conflict' },
  { id: 'act3', chapterId: 'ch1', title: '卷宗前夜', order: 2, nodeIds: ['n05','n06'], dramaticFunction: 'turn' },
  { id: 'act4', chapterId: 'ch2', title: '联络', order: 0, nodeIds: ['n07','n08a','n09a','n08b','n09b','n08c','n09c'], dramaticFunction: 'conflict' },
  { id: 'act5', chapterId: 'ch2', title: '独处', order: 1, nodeIds: ['n10','n11'], dramaticFunction: 'setup' },
  { id: 'act6', chapterId: 'ch2', title: '林德福', order: 2, nodeIds: ['n12','n13','n14a','n15a','n14b','n15b'], dramaticFunction: 'conflict' },
  { id: 'act7', chapterId: 'ch3', title: '抉择', order: 0, nodeIds: ['n16','n17'], dramaticFunction: 'turn' },
  { id: 'act8', chapterId: 'ch3', title: '展开', order: 1, nodeIds: ['n18a','n19a','n18b','n19b','n18c','n19c','n18d'], dramaticFunction: 'conflict' },
  { id: 'act9', chapterId: 'ch3', title: '结局', order: 2, nodeIds: ['n20a','n20b','n20c','n20d'], dramaticFunction: 'resolution' },
]

const nodes = [

// ── n01 START ──────────────────────────────────────────────────────────────
{
  id: 'n01', actId: 'act1', title: '深夜门铃', type: 'start', order: 0,
  position: { x: 100, y: 400 },
  emotionFunction: { emotionIn: '平静', emotionOut: '警觉', playerEmotion: '好奇', tension: 3 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静的书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '晚上十一点二十分。退休法官方静在书房看书，门铃响了。',
  dialogue: [
    dl('n01',1,'','晚上十一点二十分。方静在书房读一本植物学的书。茶已经凉了。','平静'),
    dl('n01',2,'','门铃响了。','平静'),
    dl('n01',3,'方静','[放下书，看向监控屏幕]','平静'),
    dl('n01',4,'','监控里：一个二十多岁的女人，手里抱着厚厚的文件夹，站在门口。','平静'),
    dl('n01',5,'方静','[对自己] 这个时间。','疑惑'),
    dl('n01',6,'','那个女人抬起头，直视监控镜头。她知道有人在看。','平静'),
    dl('n01',7,'陈晓晴','[对着门] 方法官，我叫陈晓晴，是记者。我知道现在很晚了。','平静'),
    dl('n01',8,'陈晓晴','我带了陈国民案的新证据。二十年前您主审的案子。','平静'),
    dl('n01',9,'','方静的手放在对讲机按钮旁边，停住了。','警觉'),
    dl('n01',10,'陈晓晴','证人陈福海承认他当年作了伪证。我有他的录像。','平静'),
    dl('n01',11,'','方静把书放到桌上，站起来了。','警觉'),
    dl('n01',12,'','她走到门口，手放在门锁上，停顿了大约五秒钟。','紧张'),
    dl('n01',13,'','外面安静，只有陈晓晴还站在那里，没有离开的意思。','平静'),
  ],
  choices: [ ch('n01',1,'继续','n02','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'setup',
},

// ── n02 BRANCH_1 ──────────────────────────────────────────────────────────
{
  id: 'n02', actId: 'act1', title: '开门还是不开', type: 'branch', order: 1,
  position: { x: 300, y: 400 },
  emotionFunction: { emotionIn: '警觉', emotionOut: '决定', playerEmotion: '犹豫', tension: 4 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家走廊', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静站在门前，手放在门锁上。',
  dialogue: [
    dl('n02',1,'','方静站在门前，手放在门锁上。','紧张'),
    dl('n02',2,'','她当了三十年法官。见过太多人在门口等待——有些人是送消息的，有些人是带麻烦来的。','平静'),
    dl('n02',3,'方静','[对自己] 陈福海。','若有所思'),
    dl('n02',4,'','那个名字她记得。证人席上那个哭了的男人。她当时注意到了那种哭法——不像是在表演。','回忆'),
    dl('n02',5,'','但那不是她的问题。那是她的判断，二十年前的判断。','防御'),
    dl('n02',6,'陈晓晴','[在门外] 我不会占用您太多时间，半小时就够。','平静'),
    dl('n02',7,'','方静深吸一口气。','紧张'),
  ],
  choices: [
    ch('n02',1,'开门，让她进来','n03a','','','heavy'),
    ch('n02',2,'关掉监控，不开门','n03b','','','heavy'),
  ],
  durationSeconds: 116, notes: '', dramaticWeight: 'dilemma',
},

// ── n03a 开门路径 ────────────────────────────────────────────────────────
{
  id: 'n03a', actId: 'act2', title: '客厅交锋', type: 'normal', order: 0,
  position: { x: 500, y: 250 },
  emotionFunction: { emotionIn: '防御', emotionOut: '职业化', playerEmotion: '审视', tension: 5 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静开了门。陈晓晴走进客厅，两人站着，没有人坐下来。',
  dialogue: [
    dl('n03a',1,'方静','[看着陈晓晴的证件] 记者证是三年前颁发的。','平静'),
    dl('n03a',2,'陈晓晴','是的。上面的照片比较老，但证件有效。','平静'),
    dl('n03a',3,'方静','你知道深夜登门拜访退休法官这件事，本身就值得怀疑。','克制'),
    dl('n03a',4,'陈晓晴','我知道。我也知道如果您不开门我就不会知道您在家。','平静'),
    dl('n03a',5,'方静','[把证件还回去] 你说陈福海。','平静'),
    dl('n03a',6,'陈晓晴','二十年前的证人，关键证人。当年他的证词确立了陈国民在案发时间的位置。','平静'),
    dl('n03a',7,'方静','他的证词是经过法庭质证的。','防御'),
    dl('n03a',8,'陈晓晴','是的。他在证人席上也哭了。您坐在法官席上，您记得吗？','直接'),
    dl('n03a',9,'','方静停顿了一下。她记得。','内心'),
    dl('n03a',10,'方静','你说他承认了伪证。','平静'),
    dl('n03a',11,'陈晓晴','三周前他联系了我。主动的。他说他活不了几年了，他想在死之前说清楚。','平静'),
    dl('n03a',12,'方静','[停顿] 活不了几年。','冷静'),
    dl('n03a',13,'陈晓晴','胰腺癌，晚期。他不是来寻求同情的，他是来纠正一个错误的。','平静'),
    dl('n03a',14,'方静','把录像给我看。','平静'),
  ],
  choices: [ ch('n03a',1,'看录像','n04a','','','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'tension',
},

// ── n04a 开门路径·看录像 ─────────────────────────────────────────────
{
  id: 'n04a', actId: 'act2', title: '陈福海的录像', type: 'normal', order: 1,
  position: { x: 700, y: 250 },
  emotionFunction: { emotionIn: '职业化', emotionOut: '动摇', playerEmotion: '震动', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '陈晓晴打开笔记本，一个老人的脸出现在屏幕上。',
  dialogue: [
    dl('n04a',1,'','屏幕上，一个六十多岁的男人坐在一张简陋的椅子上，背后是白墙。','平静'),
    dl('n04a',2,'陈福海[录像]','当年我撒了谎。我在证人席上说我看到陈国民在九点十五分到三十分之间从现场离开。我没有看到。','低沉'),
    dl('n04a',3,'陈福海[录像]','我当时受到了威胁。不是"有人找过我"那种威胁——我的意思是，我以为他们会伤害我家人。','疲惫'),
    dl('n04a',4,'','方静的手放在腿上，没有动。','内心'),
    dl('n04a',5,'陈福海[录像]','陈国民那天晚上九点到九点半，在哪里我不知道。我撒谎说我看到他离开，是因为有人需要那段时间是空白的。','低沉'),
    dl('n04a',6,'陈福海[录像]','我向陈国民道歉。我向他的家人道歉。对不起来不及，但我只能这样。','颤抖'),
    dl('n04a',7,'','录像在这里停止了。陈晓晴合上笔记本。','平静'),
    dl('n04a',8,'方静','[沉默了大约二十秒] 他说"有人需要那段时间是空白的"。','平静'),
    dl('n04a',9,'陈晓晴','是。他在后面的采访里讲了更多，但核心就是这句话。','平静'),
    dl('n04a',10,'方静','你找到那个人了？','平静'),
    dl('n04a',11,'陈晓晴','还没有。但我有了方向。方法官，我需要的是——您当年的审判记录里，有一处您可能注意到了但没有追究的地方。','直接'),
    dl('n04a',12,'方静','[站起来] 你等一下。','平静'),
    dl('n04a',13,'','她走进了书房。','内心'),
  ],
  choices: [ ch('n04a',1,'去找旧笔记','n05','','+conviction','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'reveal',
},

// ── n03b 不开门路径 ───────────────────────────────────────────────────
{
  id: 'n03b', actId: 'act2', title: '门缝里的文件', type: 'normal', order: 2,
  position: { x: 500, y: 570 },
  emotionFunction: { emotionIn: '防御', emotionOut: '被迫接触', playerEmotion: '独处', tension: 5 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家走廊', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静没有开门。门外安静了一会儿，然后一叠文件从门缝推了进来。',
  dialogue: [
    dl('n03b',1,'','方静没有开门。她站在那里，背对着门，等着。','平静'),
    dl('n03b',2,'','外面安静了大约三十秒。','平静'),
    dl('n03b',3,'','然后，一叠文件从门缝里被推进来，一张接着一张，最后是一张名片。','惊讶'),
    dl('n03b',4,'陈晓晴','[在门外] 这是复印件，我还有原件。您可以慢慢看。我明天早上再来。','平静'),
    dl('n03b',5,'','脚步声，然后是电梯的叮的一声。她走了。','平静'),
    dl('n03b',6,'','方静蹲下来，把那叠文件拿起来。','谨慎'),
    dl('n03b',7,'','陈福海的采访稿。录像截图。当年的庭审笔录复印件——不知道她从哪里弄到的。','专注'),
    dl('n03b',8,'','方静坐在走廊的地板上，开始一页一页地看。','专注'),
    dl('n03b',9,'','没有人解释，没有人引导，只有她自己去拼。','内心'),
    dl('n03b',10,'','陈福海的采访稿第三页，一句话：「我在证人席上说的是谎话，那段时间陈国民在哪里我不知道。」','震动'),
    dl('n03b',11,'','方静把那页纸放下来，在走廊里坐着，靠着墙。','空白'),
    dl('n03b',12,'','走廊的灯有感应，过了几分钟自动灭了。她没有动。','内心'),
    dl('n03b',13,'','黑暗里她摸出手机，找到林德福的号码，又放下了手机。','犹豫'),
    dl('n03b',14,'','她站起来，走到门口，把门开了一条缝，黑暗的走廊里，那叠文件还散在地上。','决定'),
  ],
  choices: [ ch('n03b',1,'进入书房，找旧笔记','n04b','','','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'tension',
},

// ── n04b 不开门路径·独自消化 ──────────────────────────────────────────
{
  id: 'n04b', actId: 'act2', title: '独自拼图', type: 'normal', order: 3,
  position: { x: 700, y: 570 },
  emotionFunction: { emotionIn: '被迫接触', emotionOut: '动摇', playerEmotion: '孤独', tension: 5 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静把文件带进书房，摊在桌上，一个人慢慢地读。',
  dialogue: [
    dl('n04b',1,'','方静把那叠文件摊在书桌上，打开台灯。','平静'),
    dl('n04b',2,'','没有人解释，没有人导读。她得自己读。','内心'),
    dl('n04b',3,'','她把庭审笔录复印件放在左边，陈福海的采访截图放在右边，开始比对。','专注'),
    dl('n04b',4,'','当年的庭审记录里，陈福海的证词：「我在9:15到9:30之间，在后巷看到被告离开。」','专注'),
    dl('n04b',5,'','采访截图里，陈福海的话：「那段时间陈国民在哪里，我不知道。那是我编的。」','震动'),
    dl('n04b',6,'','方静在「9:15到9:30」这几个字下面画了一条线。','内心'),
    dl('n04b',7,'','她在某处记得，案子当时的疑点之一，就是被告的供述里有一段时间说不清楚。','若有所思'),
    dl('n04b',8,'','陈福海的证词，恰好填补了那段时间。','震惊'),
    dl('n04b',9,'','「填补」。','内心'),
    dl('n04b',10,'','方静在这个词上停了很久。','内心'),
    dl('n04b',11,'','两点钟了，她没有睡意。她站起来，走进书房里更深处，开始找那本当年的工作笔记。','专注'),
    dl('n04b',12,'','那本笔记应该在这里。她想。三十年的案子，每一本她都没有扔。','内心'),
    dl('n04b',13,'','她在第三个抽屉找到了二十年前标注的那一本，落灰了，封面上有她当年潦草写下的年份。','发现'),
  ],
  choices: [ ch('n04b',1,'翻开笔记','n05','','+conviction','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n05 MERGE_1 发现便条 ──────────────────────────────────────────────
{
  id: 'n05', actId: 'act3', title: '旧笔记', type: 'merge', order: 0,
  position: { x: 900, y: 400 },
  emotionFunction: { emotionIn: '动摇', emotionOut: '专注', playerEmotion: '沉重', tension: 6 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静翻开二十年前的工作笔记，找到了那个案子的记录。',
  dialogue: [
    dl('n05',1,'','那本笔记的纸已经微微泛黄，但字迹清晰。方静的字，三十年没有变过，工整，偏小。','平静'),
    dl('n05',2,'','她翻到「陈国民」那个案子的记录，日期：二十年前的秋天。','专注'),
    dl('n05',3,'','庭审第一天，第二天，第三天，她的笔记密密麻麻，每一句证词她都做了标注。','专注'),
    dl('n05',4,'','她是一个仔细的法官。这一点她一直引以为傲。','内心'),
    dl('n05',5,'','第三天，陈福海出庭那天，她的笔记里有一条划掉又重写的备注，墨迹比其他地方深。','发现'),
    dl('n05',6,'','她把那页纸凑到灯下，看清楚了那条备注：','专注'),
    dl('n05',7,'','「供述时间线：晚9:15—9:30空白，待查。」','震惊'),
    dl('n05',8,'','然后是空白，下一行是完全不相关的另一个问题。','沉默'),
    dl('n05',9,'','「待查」。她当年写了「待查」。','内心'),
    dl('n05',10,'','她从来没有查。','内心'),
    dl('n05',11,'','方静把笔记放在桌上，坐着，一动不动。','空白'),
    dl('n05',12,'','台灯的光照在那两个字上，「待查」，「待查」，「待查」。','压抑'),
    dl('n05',13,'','她在这一行字旁边，看到了自己当年的字迹，看到了二十年前那个仔细的自己，选择了不仔细。','震动'),
  ],
  choices: [ ch('n05',1,'继续翻看','n06','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'reveal',
},

// ── n06 便条的分量 ────────────────────────────────────────────────────
{
  id: 'n06', actId: 'act3', title: '待查', type: 'normal', order: 1,
  position: { x: 1100, y: 400 },
  emotionFunction: { emotionIn: '专注', emotionOut: '沉重', playerEmotion: '压迫', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静坐在灯下，面对那两个字，开始回想二十年前庭审的那一天。',
  dialogue: [
    dl('n06',1,'','她想起那一天了。','内心'),
    dl('n06',2,'','第三天的庭审，下午，陈福海在证人席上说完了证词，她看了一眼那个时间段。','回忆'),
    dl('n06',3,'','她当时怎么想的？她当时想，9:15到9:30，是被告自己供述无法解释的时间段，而现在有了一个证词覆盖了它。','回忆'),
    dl('n06',4,'','她当时想，这个证词有一点太及时了。','回忆'),
    dl('n06',5,'','「太及时了。」','内心'),
    dl('n06',6,'','她记得她当时写下了「待查」，她记得她告诉自己等会儿再看，庭审有其他的问题要处理。','回忆'),
    dl('n06',7,'','然后庭审结束了，然后她的「等会儿」没有来，然后案子进入判决阶段，然后陈国民被判了无期。','回忆'),
    dl('n06',8,'','然后那两个字，「待查」，在笔记里躺了二十年，没有人动过。','震动'),
    dl('n06',9,'','她不是被欺骗的受害者。','内心'),
    dl('n06',10,'','她注意到了，她写了下来，她选择了往后推，然后就没有然后了。','压抑'),
    dl('n06',11,'','方静把那本笔记合上，把它放回抽屉里，然后重新拿出来，放在桌上。','内心'),
    dl('n06',12,'','放进去，拿出来。放进去，拿出来。','内心'),
    dl('n06',13,'','最后她把它放在桌上，走到窗前，看着窗外的夜。','压抑'),
    dl('n06',14,'','她需要做一个决定，或者先做一件事。','决定'),
  ],
  choices: [ ch('n06',1,'做决定','n07','','+conviction,+conviction','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'dilemma',
},

// ── n07 BRANCH_2 打给谁 ───────────────────────────────────────────────
{
  id: 'n07', actId: 'act4', title: '手机', type: 'branch', order: 0,
  position: { x: 1300, y: 400 },
  emotionFunction: { emotionIn: '沉重', emotionOut: '决定', playerEmotion: '困境', tension: 7 },
  systemFunction: { variablesRead: ['conviction'], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静站在窗前，手里拿着手机，屏幕亮着。',
  dialogue: [
    dl('n07',1,'','方静拿出手机，屏幕亮着，什么都没有按。','沉默'),
    dl('n07',2,'','林德福的号码在通讯录里。三十年的同事，后来是不同系统里的老朋友。','内心'),
    dl('n07',3,'','陈晓晴的名片还在桌上，或者在走廊的地板上。','内心'),
    dl('n07',4,'','或者，什么都不做。等到天亮，看事情会不会自己变得更清晰。','内心'),
    dl('n07',5,'','方静知道这三个选项意味着什么。打给林德福，是在选择走旧的关系。打给陈晓晴，是在选择站到她那边。什么都不做，是在拖延。','内心'),
    dl('n07',6,'','三十年的职业生涯里，她无数次面对无法现在做出的决定。','若有所思'),
    dl('n07',7,'','拖延有时候是智慧，有时候是懦弱。她知道两者之间的边界。','内心'),
  ],
  choices: [
    ch('n07',1,'打给林德福','n08a','','','heavy'),
    ch('n07',2,'打给陈晓晴','n08b','','','heavy'),
    ch('n07',3,'关掉手机，等到天亮','n08c','','','heavy'),
  ],
  durationSeconds: 116, notes: '', dramaticWeight: 'dilemma',
},

// ── n08a 打给林德福 ───────────────────────────────────────────────────
{
  id: 'n08a', actId: 'act4', title: '林德福接了', type: 'normal', order: 1,
  position: { x: 1500, y: 200 },
  emotionFunction: { emotionIn: '决定', emotionOut: '寒冷', playerEmotion: '被揭穿', tension: 8 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '电话接通了，林德福的声音，圆滑，像往常一样。',
  dialogue: [
    dl('n08a',1,'林德福','[电话里，声音略带沙哑] 静姐，这么晚。','平静'),
    dl('n08a',2,'方静','有个记者来找我，关于陈国民的案子。','平静'),
    dl('n08a',3,'林德福','[停顿，不到两秒] 噢，那个。','平静'),
    dl('n08a',4,'','「那个」。方静注意到了这两个字。','内心'),
    dl('n08a',5,'方静','你知道？','平静'),
    dl('n08a',6,'林德福','有人跟我提过，说有个记者在查老案子。静姐，这种事情时不时会有，不用太在意。','平静'),
    dl('n08a',7,'方静','陈福海说他当年撒了谎。','直接'),
    dl('n08a',8,'林德福','[又是一个停顿] 他现在说什么都可以，对吧。人老了，心思多。','圆滑'),
    dl('n08a',9,'方静','德福，我当年笔记里有一条「待查」的记录，关于陈国民供述的时间段。','直接'),
    dl('n08a',10,'林德福','静姐，每个案子都有值得再看的地方，这是法律的局限，不是你的问题。','安抚'),
    dl('n08a',11,'方静','[停顿] 你当时知道那个时间段的问题。','冷静'),
    dl('n08a',12,'','沉默。不是电话断了，是林德福在想怎么说。','内心'),
    dl('n08a',13,'林德福','静姐，有些事情当时的情况是那样的。证据够了，程序完整，这个案子是经得起看的。','圆滑'),
    dl('n08a',14,'方静','经得起看。','平静'),
    dl('n08a',15,'林德福','你好好休息，这件事我来处理。','结束'),
    dl('n08a',16,'','电话挂了。方静把手机放下，看着它。','空白'),
  ],
  choices: [ ch('n08a',1,'坐在黑暗里消化这件事','n09a','','+conviction','light') ],
  durationSeconds: 188, notes: '', dramaticWeight: 'reveal',
},

// ── n09a 林德福电话后 ─────────────────────────────────────────────────
{
  id: 'n09a', actId: 'act4', title: '他知道', type: 'normal', order: 2,
  position: { x: 1700, y: 200 },
  emotionFunction: { emotionIn: '寒冷', emotionOut: '清醒', playerEmotion: '孤独', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '电话挂断后，方静一个人坐在黑暗的书房里。',
  dialogue: [
    dl('n09a',1,'','电话挂了，屏幕灭了，书房里只有台灯的光。','平静'),
    dl('n09a',2,'','「那个。」','内心'),
    dl('n09a',3,'','林德福说「那个」的时候，他知道她在说什么。不是「什么陈国民」，不是「哪个案子」，是「那个」。','内心'),
    dl('n09a',4,'','「有些事情当时的情况是那样的。」','内心'),
    dl('n09a',5,'','他没有说「那个案子没有问题」。他说的是「当时的情况」。','分析'),
    dl('n09a',6,'','方静在法庭上待了三十年，她知道人们说话时怎么不说谎但也不说真话。','内心'),
    dl('n09a',7,'','「这件事我来处理。」','内心'),
    dl('n09a',8,'','他以为这是「处理」。他以为她打这个电话是在告诉他：有麻烦来了，帮我挡一下。','内心'),
    dl('n09a',9,'','方静站起来，在书房里走了两个来回。','内心'),
    dl('n09a',10,'','她现在知道了两件事。第一，当年那段时间线是有问题的，林德福知道。第二，林德福不打算承认这件事。','清醒'),
    dl('n09a',11,'','她不知道的是：当时她的「待查」没有变成「查」，是纯粹的疏忽，还是也有别的原因。','内心'),
    dl('n09a',12,'','她开始不确定自己是否真的只是疏忽了。','恐惧'),
    dl('n09a',13,'','天开始亮了，她没有睡。','疲惫'),
  ],
  choices: [ ch('n09a',1,'等待林德福登门','n10','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n08b 打给陈晓晴 ───────────────────────────────────────────────────
{
  id: 'n08b', actId: 'act4', title: '陈晓晴回来了', type: 'normal', order: 3,
  position: { x: 1500, y: 400 },
  emotionFunction: { emotionIn: '决定', emotionOut: '动容', playerEmotion: '突破', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静打给陈晓晴，对方二十分钟后回来了，这次两个人都坐了下来。',
  dialogue: [
    dl('n08b',1,'陈晓晴','[进门，看了一眼方静的样子] 您找到什么了？','克制'),
    dl('n08b',2,'方静','我当年的笔记里有一条「待查」，关于陈国民供述里的时间段。我没有查。','直接'),
    dl('n08b',3,'陈晓晴','[停顿] 9:15到9:30。','平静'),
    dl('n08b',4,'方静','你知道。','平静'),
    dl('n08b',5,'陈晓晴','那是整个案子最重要的十五分钟。陈福海的证词刚好覆盖了它。','直接'),
    dl('n08b',6,'方静','我当时注意到了。我写了「待查」，然后案子走完了，我没有回去查。','直接'),
    dl('n08b',7,'陈晓晴','[长时间的沉默]','沉默'),
    dl('n08b',8,'方静','我不是在找借口。我在陈述一个事实。','克制'),
    dl('n08b',9,'陈晓晴','我知道。','低沉'),
    dl('n08b',10,'陈晓晴','我父亲判决那一年，我十一岁。我妈带我去探视，他隔着玻璃问我期末考了多少分。','低沉'),
    dl('n08b',11,'','方静没有动。','内心'),
    dl('n08b',12,'陈晓晴','他在里面过得很不好，但他从来不让我们知道。他说「我没有做」，一直说，说了二十年。','颤抖'),
    dl('n08b',13,'陈晓晴','他不是让我来找一个交代的。他让我来弄清楚这件事，弄清楚真相是什么，无论结果。','坚定'),
    dl('n08b',14,'方静','[停顿很久] 我需要看原始案卷。','平静'),
  ],
  choices: [ ch('n08b',1,'送走陈晓晴，独处','n09b','','+conviction','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'payoff',
},

// ── n09b 晓晴离开后 ───────────────────────────────────────────────────
{
  id: 'n09b', actId: 'act4', title: '十一岁', type: 'normal', order: 4,
  position: { x: 1700, y: 400 },
  emotionFunction: { emotionIn: '动容', emotionOut: '沉重', playerEmotion: '无法回避', tension: 6 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '陈晓晴离开后，方静一个人坐在客厅里，台灯还开着。',
  dialogue: [
    dl('n09b',1,'','陈晓晴走了，客厅里很安静。','平静'),
    dl('n09b',2,'','「十一岁。」','内心'),
    dl('n09b',3,'','方静当了三十年法官，她见过数不清的案件，读过数不清的卷宗。','内心'),
    dl('n09b',4,'','她在判决书里见过「受害者」「被告」「证人」，她很少想到「女儿」「妻子」「十一岁」。','内心'),
    dl('n09b',5,'','这不是在说她冷漠。这是职业训练的结果——你必须抽象化，你才能公正。','内心'),
    dl('n09b',6,'','但是，「公正」和「抽象化」本来不应该是一回事。','内心'),
    dl('n09b',7,'','她站起来，走进书房，把那本笔记从桌上拿起来，翻到那一页。','专注'),
    dl('n09b',8,'','「待查。」','内心'),
    dl('n09b',9,'','她当年那个「待查」，变成了一个十一岁的女孩二十年没有父亲陪。','震动'),
    dl('n09b',10,'','不是这么简单的逻辑，她知道。法律的错误不能只看结果。','内心'),
    dl('n09b',11,'','但是，她也知道，那个十一岁的女孩坐在这里，把这件事说出来，不是在讲法律。','清醒'),
    dl('n09b',12,'','天快亮了。方静把台灯关掉，在黑暗里坐着，等林德福来。','内心'),
    dl('n09b',13,'','她知道他会来的。这种事情，他不会让它自己发展。','清醒'),
  ],
  choices: [ ch('n09b',1,'等待天亮','n10','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n08c 什么都不做 ───────────────────────────────────────────────────
{
  id: 'n08c', actId: 'act4', title: '黑暗中等待', type: 'normal', order: 5,
  position: { x: 1500, y: 600 },
  emotionFunction: { emotionIn: '决定', emotionOut: '瘫痪', playerEmotion: '漂浮', tension: 6 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静什么都没做，把手机放下，一个人坐在书房的黑暗里。',
  dialogue: [
    dl('n08c',1,'','方静把手机放下，关灯，坐在黑暗里。','平静'),
    dl('n08c',2,'','这是她做过最多的事——等。等事情更清晰，等情绪退去，等时机成熟。','内心'),
    dl('n08c',3,'','三十年里，她学会了不被情绪推着走。她学会了先停一停，先想清楚再行动。','内心'),
    dl('n08c',4,'','但现在，停下来，什么都没有变清晰，只是夜越来越深了。','内心'),
    dl('n08c',5,'','那本旧笔记在桌上，台灯灭了，她看不见，但她知道那行字在哪里。','内心'),
    dl('n08c',6,'','「待查。」','内心'),
    dl('n08c',7,'','她睡着了，或者说她以为她睡着了，后来她也没有分清楚那个夜晚哪部分是梦。','空白'),
    dl('n08c',8,'','天亮了。七点半，她的手机响了，一个推送消息。','平静'),
    dl('n08c',9,'','她点开，是陈晓晴的署名文章，刚发出来，题目：《一个错案的二十年》。','震惊'),
    dl('n08c',10,'','文章写得很克制，只写了案情，没有点任何人的名字，包括她。','平静'),
    dl('n08c',11,'','「目前，相关知情人士尚未回应本报采访请求。」','平静'),
    dl('n08c',12,'','方静把手机放下，走到窗边，看着楼下早晨上班的人流。','内心'),
    dl('n08c',13,'','她昨晚选择了等待。结果，她已经没有等待的时间了。','清醒'),
  ],
  choices: [ ch('n08c',1,'面对新的一天','n09c','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n09c 看到报道发出 ─────────────────────────────────────────────────
{
  id: 'n09c', actId: 'act4', title: '第一篇报道', type: 'normal', order: 6,
  position: { x: 1700, y: 600 },
  emotionFunction: { emotionIn: '瘫痪', emotionOut: '紧迫', playerEmotion: '失去主动权', tension: 8 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'DAWN', interior: 'INT' },
  sceneDesc: '方静把文章读完了，第一篇，她不在里面。但第二篇呢？',
  dialogue: [
    dl('n09c',1,'','方静把文章读完了，一字一句，三遍。','专注'),
    dl('n09c',2,'','第一遍，她在看措辞。第二遍，她在找自己的名字。第三遍，她在想下一篇会写什么。','分析'),
    dl('n09c',3,'','文章里提到了当年的主要证人，提到了证词的细节，提到了案件的判决结果。没有点任何人的名。','平静'),
    dl('n09c',4,'','「相关知情人士尚未回应本报采访请求。」','内心'),
    dl('n09c',5,'','她是「知情人士」之一。这句话她知道是在等她回应。','清醒'),
    dl('n09c',6,'','如果她不回应，第二篇会写什么？','内心'),
    dl('n09c',7,'','如果她回应，说什么？','内心'),
    dl('n09c',8,'','她昨晚有机会打电话，她没有打。她昨晚有机会开门，有人开了，有人没开。','内心'),
    dl('n09c',9,'','无论如何，现在报道已经发出了，主动权不在她手里了。','清醒'),
    dl('n09c',10,'','方静把手机放下，走进厨房，烧了一壶水，站在那里等水开。','内心'),
    dl('n09c',11,'','门铃响了，是林德福，她没有看监控就知道是他。','清醒'),
    dl('n09c',12,'','这种事情，他不会让它自己发展的。','内心'),
    dl('n09c',13,'','方静开了门。','决定'),
  ],
  choices: [ ch('n09c',1,'让林德福进来','n10','','+conviction','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n10 MERGE_2 林德福登门 ────────────────────────────────────────────
{
  id: 'n10', actId: 'act5', title: '林德福来了', type: 'merge', order: 0,
  position: { x: 1900, y: 400 },
  emotionFunction: { emotionIn: '各异', emotionOut: '警觉', playerEmotion: '对峙前', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '林德福带着茶叶来了，像来看老朋友。',
  dialogue: [
    dl('n10',1,'林德福','[递上茶叶] 新茶，我知道你喝这个。','自然'),
    dl('n10',2,'方静','[接过来] 坐。','平静'),
    dl('n10',3,'林德福','你气色不好，没睡好？','关心'),
    dl('n10',4,'方静','茶还没烧，你等一下。','平静'),
    dl('n10',5,'','方静去厨房烧水，林德福在客厅站了一会儿，然后坐下，把客厅扫了一眼。','内心'),
    dl('n10',6,'','桌上放着一本旧笔记。','观察'),
    dl('n10',7,'林德福','[方静回来后] 最近怎么样，适应退休生活了吗？','随意'),
    dl('n10',8,'方静','习惯了。你来不是为了问这个的。','直接'),
    dl('n10',9,'林德福','[笑了一下] 咱们认识三十年了，我就是来看看你。','圆滑'),
    dl('n10',10,'方静','你昨晚接了我的电话。或者，你今天来，是因为某个记者也联系了你。','直接'),
    dl('n10',11,'林德福','[停顿] 静姐，你什么时候变得这么多疑了。','安抚'),
    dl('n10',12,'方静','我一直这样。你只是不适应我不给你面子这件事。','克制'),
    dl('n10',13,'','沉默。茶壶开始叫了。','沉默'),
  ],
  choices: [ ch('n10',1,'去倒茶，继续谈','n11','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n11 EXPLORE 镜中独白 ────────────────────────────────────────────
{
  id: 'n11', actId: 'act5', title: '镜子', type: 'explore', order: 1,
  position: { x: 2100, y: 400 },
  emotionFunction: { emotionIn: '警觉', emotionOut: '清醒', playerEmotion: '沉入内心', tension: 6 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家卫生间', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静借口去拿茶杯，走到卫生间，看着镜子里的自己。',
  dialogue: [
    dl('n11',1,'','方静站在镜子前，冷水开着，手放在水流里，没有洗手。','平静'),
    dl('n11',2,'','她看着镜子里的自己，六十五岁，白发，脸上是三十年法官生涯的痕迹。','内心'),
    dl('n11',3,'','她当了三十年法官，她的名声是「铁面无私」。她以为她理解这四个字。','内心'),
    dl('n11',4,'','「铁面」——不被情绪左右。「无私」——不被利益影响。','内心'),
    dl('n11',5,'','但是，「待查」这两个字，当时她为什么没有查？','内心'),
    dl('n11',6,'','不是利益，不是情绪。是什么？','内心'),
    dl('n11',7,'','是「差不多了」。','内心'),
    dl('n11',8,'','「这个案子证据够了，程序完整，就这样吧。」','内心'),
    dl('n11',9,'','她当时有这个念头，一个微小的、说不出口的念头，然后她让它消失了，继续往下走。','内心'),
    dl('n11',10,'','「铁面无私」的人，也可以有「差不多了」的念头。她以为那不重要，因为她从来没有付诸行动。','内心'),
    dl('n11',11,'','但是「待查」没有变成「查」，那个念头就变成了一个行动。','震动'),
    dl('n11',12,'','她关掉冷水，拿起毛巾，看了最后一眼镜子里的自己。','决定'),
    dl('n11',13,'','客厅里，林德福在等她。','清醒'),
  ],
  choices: [ ch('n11',1,'回到客厅','n12','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'reveal',
},

// ── n12 林德福谈话 ────────────────────────────────────────────────────
{
  id: 'n12', actId: 'act6', title: '茶和旧交情', type: 'normal', order: 0,
  position: { x: 2300, y: 400 },
  emotionFunction: { emotionIn: '清醒', emotionOut: '对峙', playerEmotion: '压迫', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静回到客厅，林德福已经把茶倒好了，两个人对坐。',
  dialogue: [
    dl('n12',1,'林德福','那个记者，叫陈晓晴，是陈国民的女儿。','平静'),
    dl('n12',2,'方静','我知道。','平静'),
    dl('n12',3,'林德福','静姐，你知道这种事情是怎么操作的。她现在拿着一个陈年证人的反悔声明，想翻一个二十年前的旧案。','分析'),
    dl('n12',4,'林德福','陈福海的证词经过了法庭质证，当时律师没有提出异议，你也没有。程序是完整的。','圆滑'),
    dl('n12',5,'方静','陈福海承认他撒了谎。','直接'),
    dl('n12',6,'林德福','他现在说他撒了谎，你能怎么验证？他是垂死的老人，他说什么媒体都愿意信。','圆滑'),
    dl('n12',7,'方静','[看着林德福] 你来，是要告诉我什么？','直接'),
    dl('n12',8,'林德福','[喝了一口茶] 我来是因为担心你。你退休了，好不容易清静了，不要让这件事搅乱你。','圆滑'),
    dl('n12',9,'方静','如果案子是错的，它本来就不该是清静的。','克制'),
    dl('n12',10,'林德福','[停顿] 静姐，你我都知道，不是每个案子都是百分之百的。程序正确，证据充分，这是我们能做到的极限。','辩护'),
    dl('n12',11,'林德福','你一个案子查下去，受影响的不只是这一个案子，是你三十年做过的所有案子。','警告'),
    dl('n12',12,'方静','你在警告我？','冷静'),
    dl('n12',13,'林德福','[站起来准备离开] 我在关心你。','坚持'),
  ],
  choices: [ ch('n12',1,'送林德福到门口，做决定','n13','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n13 BRANCH_3 面对林德福离开时 ──────────────────────────────────────
{
  id: 'n13', actId: 'act6', title: '送客', type: 'branch', order: 1,
  position: { x: 2500, y: 400 },
  emotionFunction: { emotionIn: '对峙', emotionOut: '决断', playerEmotion: '关键时刻', tension: 8 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家门口', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '林德福走向门口，方静跟着他。',
  dialogue: [
    dl('n13',1,'','林德福站起来，走向门口。方静跟着他。','平静'),
    dl('n13',2,'林德福','想开一点，静姐，你这辈子做得很好。','圆滑'),
    dl('n13',3,'','方静站在门口，林德福的手已经放在门把上了。','内心'),
    dl('n13',4,'','她有一秒钟的窗口。','内心'),
    dl('n13',5,'','说，或者不说。','内心'),
    dl('n13',6,'','说什么。','内心'),
  ],
  choices: [
    ch('n13',1,'「德福，你当年知道那段时间的问题。」——直接质问','n14a','','','critical'),
    ch('n13',2,'「好，你说得对，我再想想。」——送走他，然后自己行动','n14b','','','critical'),
  ],
  durationSeconds: 108, notes: '', dramaticWeight: 'dilemma',
},

// ── n14a 直接质问 ─────────────────────────────────────────────────────
{
  id: 'n14a', actId: 'act6', title: '你知道', type: 'normal', order: 2,
  position: { x: 2700, y: 280 },
  emotionFunction: { emotionIn: '决断', emotionOut: '对抗', playerEmotion: '直面', tension: 9 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家门口', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静叫住了林德福，直接问出了那句话。',
  dialogue: [
    dl('n14a',1,'方静','德福，你当年知道那段时间线有问题。','平静'),
    dl('n14a',2,'','林德福的手停在门把上，没有动。','沉默'),
    dl('n14a',3,'林德福','[没有回头] 静姐——','圆滑'),
    dl('n14a',4,'方静','不用解释。我只想知道你知不知道。','直接'),
    dl('n14a',5,'','林德福转过来，看着她。他的脸很平静，但他的眼睛告诉了她答案。','内心'),
    dl('n14a',6,'林德福','「知道」和「能做什么」是两件事。','低沉'),
    dl('n14a',7,'方静','你能做的是不让我查那两个字。','冷静'),
    dl('n14a',8,'林德福','[停顿] 我没有阻止过你做任何事。','辩护'),
    dl('n14a',9,'方静','「差不多了，程序完整」。你不是第一次说这句话。','克制'),
    dl('n14a',10,'林德福','[声音低了一点] 静姐，有些事情翻出来不会只影响陈国民这一个案子。你清楚的。','警告'),
    dl('n14a',11,'方静','所以你来是为了保护谁？','直接'),
    dl('n14a',12,'林德福','[沉默了几秒，然后推开了门] 好好保重。','结束'),
    dl('n14a',13,'','门关上了，方静站在原地，听着电梯的声音消失。','空白'),
    dl('n14a',14,'','他承认了，但他也告诉了她代价。','清醒'),
  ],
  choices: [ ch('n14a',1,'回到书桌前','n15a','','+conviction,+conviction','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'payoff',
},

// ── n15a 对抗后 ───────────────────────────────────────────────────────
{
  id: 'n15a', actId: 'act6', title: '林德福的最后一句话', type: 'normal', order: 3,
  position: { x: 2900, y: 280 },
  emotionFunction: { emotionIn: '对抗', emotionOut: '孤独清醒', playerEmotion: '独自承担', tension: 8 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静一个人站在客厅里，消化刚才发生的事。',
  dialogue: [
    dl('n15a',1,'','方静在客厅里站了很久，没有动。','平静'),
    dl('n15a',2,'','「有些事情翻出来不会只影响陈国民这一个案子。」','内心'),
    dl('n15a',3,'','她知道这句话的意思。翻这个案子，意味着质疑程序，质疑证词质证，质疑审判的有效性。','分析'),
    dl('n15a',4,'','它的影响不会停在陈国民这里。','内心'),
    dl('n15a',5,'','她当了三十年法官，经手的案子几百个，她的名声，她的判决，都会被重新审视。','内心'),
    dl('n15a',6,'','「你清楚的。」','内心'),
    dl('n15a',7,'','她清楚。她一直清楚。这是林德福第一次把这件事说得这么明白。','内心'),
    dl('n15a',8,'','但是，她现在不得不面对的问题是：她是因为清楚代价才没有查「待查」，还是因为「差不多了」？','内心'),
    dl('n15a',9,'','她不知道。她真的不知道。','困惑'),
    dl('n15a',10,'','方静走到书桌前，把那本旧笔记打开，翻到那一页，拿起一支笔。','决定'),
    dl('n15a',11,'','「待查」旁边，她写上了今天的日期。','专注'),
    dl('n15a',12,'','她现在在查了。','决定'),
  ],
  choices: [ ch('n15a',1,'做最后的决定','n16','','','light') ],
  durationSeconds: 156, notes: '', dramaticWeight: 'tension',
},

// ── n14b 装作接受 ─────────────────────────────────────────────────────
{
  id: 'n14b', actId: 'act6', title: '送他出门', type: 'normal', order: 4,
  position: { x: 2700, y: 520 },
  emotionFunction: { emotionIn: '决断', emotionOut: '暗中确定', playerEmotion: '隐忍', tension: 8 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家门口', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静微笑着送林德福出门，门关上后，她立刻拨出一个号码。',
  dialogue: [
    dl('n14b',1,'方静','好。你说得有道理，我再想想。','平静'),
    dl('n14b',2,'林德福','[松了一口气] 就是这样，静姐，你想清楚就好。','如释重负'),
    dl('n14b',3,'方静','茶不错，下次带多点。','平静'),
    dl('n14b',4,'林德福','好，好。','如释重负'),
    dl('n14b',5,'','林德福走了，方静关上门，在门后站了三秒。','内心'),
    dl('n14b',6,'','然后她走到书桌前，拿起手机，找到一个名字：范晖，律师，她认识二十多年的朋友，和林德福没有任何关系的朋友。','专注'),
    dl('n14b',7,'方静','[打过去] 老范，我手里有一个案子需要你帮我看一下，你现在方便吗？','平静'),
    dl('n14b',8,'范晖[电话]','方法官，什么案子？','好奇'),
    dl('n14b',9,'方静','二十年前的一个故意杀人，我主审的，现在有新证据。你看完告诉我申诉程序的可行性。','直接'),
    dl('n14b',10,'范晖[电话]','[停顿] 你主审的案子，你要提申诉？','困惑'),
    dl('n14b',11,'方静','是。我发给你。','平静'),
    dl('n14b',12,'','她挂掉电话，把所有材料整理好，发了过去。','专注'),
    dl('n14b',13,'','她比任何时候都更清醒，更确定。','清醒'),
    dl('n14b',14,'','她知道她在干什么，知道它意味着什么，知道林德福那边会有反应。','清醒'),
  ],
  choices: [ ch('n14b',1,'做最后的决定','n16','','+conviction','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'tension',
},

// ── n15b 暗中行动后 ───────────────────────────────────────────────────
{
  id: 'n15b', actId: 'act6', title: '布局', type: 'normal', order: 5,
  position: { x: 2900, y: 520 },
  emotionFunction: { emotionIn: '暗中确定', emotionOut: '有准备', playerEmotion: '主动', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: ['conviction'], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静把所有材料整理好，等待律师的回复，心里有了方向。',
  dialogue: [
    dl('n15b',1,'','律师范晖三小时后回复了：申诉是可行的，但需要更多的直接证据，陈福海的证词是第一步，但不够。','平静'),
    dl('n15b',2,'','方静把这条回复看了三遍。','专注'),
    dl('n15b',3,'','「需要更多直接证据。」','内心'),
    dl('n15b',4,'','她想到了那段时间线，9:15到9:30，十五分钟的空白。陈国民当年说不清楚他在哪里，那不一定是因为他做了什么——也可能是因为他在做某件他不想说的事，一件无关案子的私事。','分析'),
    dl('n15b',5,'','如果能找到他当时真正在做什么，就能打破那段空白。','分析'),
    dl('n15b',6,'','陈晓晴找了三年，她应该有这些线索。','内心'),
    dl('n15b',7,'','方静找到陈晓晴的名片，拿起手机。这次她没有犹豫。','决定'),
    dl('n15b',8,'方静','[打过去] 陈晓晴，我有一个问题，关于那十五分钟，你查过陈国民当时可能在哪里吗？','直接'),
    dl('n15b',9,'陈晓晴[电话]','[沉默了一下] 查过，我有一些线索，但我一直缺一个——缺一个愿意说话的人。','平静'),
    dl('n15b',10,'方静','你需要我。','平静'),
    dl('n15b',11,'陈晓晴[电话]','是的。','平静'),
    dl('n15b',12,'方静','我需要时间考虑以什么形式合作。','平静'),
    dl('n15b',13,'陈晓晴[电话]','我知道。随时。','平静'),
  ],
  choices: [ ch('n15b',1,'最后的决定','n16','','+conviction','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'setup',
},

// ── n16 MERGE_3 ────────────────────────────────────────────────────────
{
  id: 'n16', actId: 'act7', title: '夜里的书桌', type: 'merge', order: 0,
  position: { x: 3100, y: 400 },
  emotionFunction: { emotionIn: '各异', emotionOut: '平静的决断', playerEmotion: '沉淀', tension: 7 },
  systemFunction: { variablesRead: ['conviction'], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '又是夜里，方静一个人坐在书桌前，面对着所有的证据和那本旧笔记。',
  dialogue: [
    dl('n16',1,'','夜里十一点，和昨晚一样的时间，方静又一个人坐在书桌前。','平静'),
    dl('n16',2,'','但昨晚和今晚之间，发生了很多事。','内心'),
    dl('n16',3,'','那本旧笔记摊开在桌上，「待查」旁边写着今天的日期，或者还是只有那两个字，等着她。','内心'),
    dl('n16',4,'','材料放在一边，陈晓晴的名片放在一边，林德福的那句话还在她耳朵里。','内心'),
    dl('n16',5,'','她当了三十年法官，她判过无数个案子，她从来没有判过自己。','内心'),
    dl('n16',6,'','但是今晚，她需要。','内心'),
    dl('n16',7,'','她需要判的不是陈国民的案子，那个交给法律去做。','内心'),
    dl('n16',8,'','她需要判的是：她，方静，六十五岁，退休法官，接下来，做什么。','内心'),
    dl('n16',9,'','不是「应该」做什么，是她，方静，想做什么。','内心'),
    dl('n16',10,'','她坐了很久，台灯的光没有变，窗外的夜没有变，只有她在慢慢变得清晰。','内心'),
    dl('n16',11,'','她拿起了手机。','决定'),
  ],
  choices: [ ch('n16',1,'做出最终决定','n17','','','light') ],
  durationSeconds: 148, notes: '', dramaticWeight: 'setup',
},

// ── n17 BRANCH_4 最终决定 ─────────────────────────────────────────────
{
  id: 'n17', actId: 'act7', title: '最终决定', type: 'branch', order: 1,
  position: { x: 3300, y: 400 },
  emotionFunction: { emotionIn: '平静的决断', emotionOut: '行动', playerEmotion: '不可撤回', tension: 9 },
  systemFunction: { variablesRead: ['conviction','courage'], variablesWrite: ['courage'], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静手里拿着手机，面对最后的选择。',
  dialogue: [
    dl('n17',1,'','方静看着手机屏幕，通讯录还开着。','平静'),
    dl('n17',2,'','三十年里，她从来没有在法庭上做过和「我」相关的决定。她的决定是关于事实，关于法律，关于那个坐在被告席上的人。','内心'),
    dl('n17',3,'','但现在，这个决定，只关于她。','内心'),
    dl('n17',4,'','她不知道哪个选择是对的，她现在只知道她会做什么。','内心'),
  ],
  choices: [
    ch('n17',1,'打给陈晓晴，说「我配合你」——公开陈述','n18a','','courage=true','critical'),
    ch('n17',2,'给林德福发短信：「你知道我手里有什么」——私下施压','n18b','','courage=true','critical'),
    ch('n17',3,'把陈晓晴的文件夹放到门口，关上门——拒绝','n18c','','','critical'),
    ch('n17',4,'打开录音软件，录制陈述——寄给最高院','n18d','conviction>=8','courage=true','critical'),
  ],
  durationSeconds: 100, notes: '', dramaticWeight: 'dilemma',
},

// ── n18a 公开路径 ──────────────────────────────────────────────────────
{
  id: 'n18a', actId: 'act8', title: '我配合你', type: 'normal', order: 0,
  position: { x: 3500, y: 180 },
  emotionFunction: { emotionIn: '行动', emotionOut: '承诺', playerEmotion: '不可撤回', tension: 8 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静拨出陈晓晴的电话。',
  dialogue: [
    dl('n18a',1,'','方静找到陈晓晴的号码，按下拨出。','平静'),
    dl('n18a',2,'陈晓晴[电话]','[两声铃后接通] 方法官？','惊讶'),
    dl('n18a',3,'方静','我配合你。','平静'),
    dl('n18a',4,'','沉默。大约十秒钟。','沉默'),
    dl('n18a',5,'陈晓晴[电话]','[声音有点变了] 您知道这意味着什么吗？','克制'),
    dl('n18a',6,'方静','我知道。','平静'),
    dl('n18a',7,'陈晓晴[电话]','我需要您在文章里，以您的名义，承认您当年注意到了时间线问题，但没有追究。','直接'),
    dl('n18a',8,'方静','我知道你需要什么。我写一份书面陈述，你来看。','平静'),
    dl('n18a',9,'陈晓晴[电话]','[又是沉默] 方法官……谢谢您。','低沉'),
    dl('n18a',10,'方静','不用谢，这是我应该做的。二十年前就应该做的。','平静'),
    dl('n18a',11,'','她挂掉电话，把手机放在桌上，开始在电脑上打开一个新的文档。','专注'),
    dl('n18a',12,'','她想了一下，开始打第一行字：「我是方静，退休法官，以下是我对二十年前一个案件的陈述。」','平静'),
    dl('n18a',13,'','她打字的时候，手没有抖。','坚定'),
  ],
  choices: [ ch('n18a',1,'继续写陈述','n19a','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'payoff',
},

// ── n19a 发出前夜 ──────────────────────────────────────────────────────
{
  id: 'n19a', actId: 'act8', title: '发出前夜', type: 'normal', order: 1,
  position: { x: 3700, y: 180 },
  emotionFunction: { emotionIn: '承诺', emotionOut: '平静', playerEmotion: '等待', tension: 6 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '陈晓晴的办公室', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '文章发出前的晚上，方静和陈晓晴坐在一起。',
  dialogue: [
    dl('n19a',1,'','文章发出的前一天晚上，陈晓晴约方静见面，在她的办公室，两个人坐了很久。','平静'),
    dl('n19a',2,'陈晓晴','方法官，文章里关于您的部分，我给您看最终版本。','认真'),
    dl('n19a',3,'方静','[看完] 可以。','平静'),
    dl('n19a',4,'陈晓晴','您确定吗？一旦发出，就没有办法取消了。','确认'),
    dl('n19a',5,'方静','我知道。','平静'),
    dl('n19a',6,'','沉默了一会儿。','沉默'),
    dl('n19a',7,'陈晓晴','我父亲不知道我来找过您。','低沉'),
    dl('n19a',8,'方静','[停顿] 他知道这件事在进行吗？','平静'),
    dl('n19a',9,'陈晓晴','他知道我在查，但他不知道进展到哪一步了。他说……他说无论结果，他都接受。','低沉'),
    dl('n19a',10,'方静','他说「接受」。','若有所思'),
    dl('n19a',11,'陈晓晴','是。他是这样的人，一直是。','低沉'),
    dl('n19a',12,'方静','告诉他，有一个人对他说抱歉。不代表法律，代表她自己。','平静'),
    dl('n19a',13,'陈晓晴','[看着方静] 我会告诉他的。','郑重'),
    dl('n19a',14,'','两个人又坐了一会儿，没有说话，外面是深夜的城市。','平静'),
  ],
  choices: [ ch('n19a',1,'结局','n20a','','','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'relief',
},

// ── n18b 私下施压路径 ─────────────────────────────────────────────────
{
  id: 'n18b', actId: 'act8', title: '你知道我手里有什么', type: 'normal', order: 2,
  position: { x: 3500, y: 360 },
  emotionFunction: { emotionIn: '行动', emotionOut: '等待', playerEmotion: '博弈', tension: 8 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静发出一条短信，然后等待。',
  dialogue: [
    dl('n18b',1,'','方静打开和林德福的短信对话，输入了一行字。','专注'),
    dl('n18b',2,'','「你知道我手里有什么。」','内心'),
    dl('n18b',3,'','她发出去了，把手机放在桌上，等。','等待'),
    dl('n18b',4,'','林德福五分钟后回复了。','平静'),
    dl('n18b',5,'林德福[短信]','「你想要什么。」','冷静'),
    dl('n18b',6,'方静[短信]','「我不想要什么，我想要陈国民的问题得到处理。」','平静'),
    dl('n18b',7,'林德福[短信]','「处理需要时间。」','圆滑'),
    dl('n18b',8,'方静[短信]','「你有多少时间？」','平静'),
    dl('n18b',9,'林德福[短信]','「两个月。」','圆滑'),
    dl('n18b',10,'','方静把手机放下，在桌上坐了很久。','内心'),
    dl('n18b',11,'','「两个月」意味着他会安排什么——不是重审，不是公开，是假释，或者某种安静的行政处理。','分析'),
    dl('n18b',12,'','不是真正的公正，但陈国民可以出来。','内心'),
    dl('n18b',13,'','方静在这两件事之间想了很久：「真正的公正」和「陈国民出来」。','内心'),
    dl('n18b',14,'','她回复了：「两个月。」','平静'),
  ],
  choices: [ ch('n18b',1,'等待结果','n19b','','','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'tension',
},

// ── n19b 私下路径·林德福回应 ────────────────────────────────────────
{
  id: 'n19b', actId: 'act8', title: '安排好了', type: 'normal', order: 3,
  position: { x: 3700, y: 360 },
  emotionFunction: { emotionIn: '等待', emotionOut: '复杂', playerEmotion: '不知道算不算赢', tension: 7 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '六周后，林德福发来消息。',
  dialogue: [
    dl('n19b',1,'','六周后，林德福发来一条短信：「安排好了，你知道的那个人，下个月可以见家人了。」','平静'),
    dl('n19b',2,'','方静把这条短信看了很久。','内心'),
    dl('n19b',3,'','假释，或者提前释放，不是平反，不是重审，不是公开承认有错。','分析'),
    dl('n19b',4,'','陈国民出来，不知道为什么出来，法律上他还是「那个案子的罪犯」。','内心'),
    dl('n19b',5,'','陈晓晴的报道，第一篇还在，后续的没有发出来，她在等方静。','内心'),
    dl('n19b',6,'','方静给陈晓晴发了一条短信，说陈国民下个月会出来。','平静'),
    dl('n19b',7,'陈晓晴[短信]','怎么安排的？','平静'),
    dl('n19b',8,'方静[短信]','不是重审，是行政程序。','平静'),
    dl('n19b',9,'陈晓晴[短信]','他出来了，但案子还在。','平静'),
    dl('n19b',10,'方静[短信]','是的。','平静'),
    dl('n19b',11,'陈晓晴[短信]','好。谢谢您。','平静'),
    dl('n19b',12,'','方静把手机放下。','内心'),
    dl('n19b',13,'','她不知道这算不算做了正确的事。她知道陈国民下个月可以和陈晓晴见面了。','内心'),
    dl('n19b',14,'','她决定，暂时，这就够了。','内心'),
  ],
  choices: [ ch('n19b',1,'结局','n20b','','','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'tension',
},

// ── n18c 拒绝路径 ─────────────────────────────────────────────────────
{
  id: 'n18c', actId: 'act8', title: '关门', type: 'normal', order: 4,
  position: { x: 3500, y: 540 },
  emotionFunction: { emotionIn: '行动', emotionOut: '封闭', playerEmotion: '放弃', tension: 6 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家门口', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静把陈晓晴的文件夹放到门口，等她来取。',
  dialogue: [
    dl('n18c',1,'','方静把陈晓晴留下的材料整理好，装回文件夹，走到门口，打开门，把它放在外面的地垫上。','平静'),
    dl('n18c',2,'','她给陈晓晴发了一条短信：「东西在门口，自己来拿。」','平静'),
    dl('n18c',3,'','陈晓晴二十分钟后来了，按了门铃，方静没有开门。','平静'),
    dl('n18c',4,'','她听到门铃声，听到走廊里的脚步声，听到文件夹被拿走的声音。','内心'),
    dl('n18c',5,'','然后是沉默。她以为陈晓晴走了。','内心'),
    dl('n18c',6,'陈晓晴','[在门外，声音很平静] 方法官，我父亲二十年了。不管您做不做，我会继续查的。','平静'),
    dl('n18c',7,'陈晓晴','但是，您的那本笔记里，有一行「待查」。那不是我写的，是您写的。','平静'),
    dl('n18c',8,'陈晓晴','我不是来审判您的，我只是想让您知道，我知道那两个字在那里。','平静'),
    dl('n18c',9,'','走廊里安静了，脚步声走远，电梯叮的一声。','沉默'),
    dl('n18c',10,'方静','[在门内，对自己] 我知道。','低沉'),
    dl('n18c',11,'','她走回书房，把那本笔记翻到那一页，把它合上，放进抽屉，锁上。','空白'),
    dl('n18c',12,'','她去烧了一壶水，做了一杯茶，坐在窗边。','平静'),
    dl('n18c',13,'','外面是正常的城市，正常的下午，什么都没有发生过。','空洞'),
  ],
  choices: [ ch('n18c',1,'独自坐着','n19c','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n19c 拒绝后 ───────────────────────────────────────────────────────
{
  id: 'n19c', actId: 'act8', title: '那本笔记', type: 'normal', order: 5,
  position: { x: 3700, y: 540 },
  emotionFunction: { emotionIn: '封闭', emotionOut: '空洞', playerEmotion: '遗留', tension: 5 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'DUSK', interior: 'INT' },
  sceneDesc: '傍晚，方静独自坐在书房，那本笔记在抽屉里。',
  dialogue: [
    dl('n19c',1,'','傍晚，方静在书房里坐了很久，什么都没做。','空洞'),
    dl('n19c',2,'','那本笔记在抽屉里，锁着。','内心'),
    dl('n19c',3,'','她拿出钥匙，把抽屉打开，把笔记拿出来，放在桌上。没有打开。','内心'),
    dl('n19c',4,'','她在想林德福那句话：「你三十年做过的所有案子。」','内心'),
    dl('n19c',5,'','她想，如果她三十年都做对了，那么一个「待查」没有查，是很小的事。','内心'),
    dl('n19c',6,'','她想，如果她三十年都做对了，那么这一个「待查」就是整个三十年里最不应该发生的事。','内心'),
    dl('n19c',7,'','两件事不能同时为真，但它们一直在她脑子里同时存在。','困惑'),
    dl('n19c',8,'','她没有打开笔记，但她也没有把它放回去。','内心'),
    dl('n19c',9,'','它在桌上放着，和那行「待查」一起，在那里。','内心'),
    dl('n19c',10,'','儿子今晚打来电话，她接了，说了十分钟的正常的话——天气，健康，他最近的工作。','平静'),
    dl('n19c',11,'','她没有说陈晓晴，没有说陈国民，没有说那本笔记。','内心'),
    dl('n19c',12,'','挂电话后，她坐在黑暗里，等着看这件事会不会自己有一个结果。','空洞'),
    dl('n19c',13,'','她知道，她也有可能永远在等。','内心'),
  ],
  choices: [ ch('n19c',1,'结局','n20c','','','light') ],
  durationSeconds: 164, notes: '', dramaticWeight: 'tension',
},

// ── n18d 录制陈述（隐藏路径） ─────────────────────────────────────────
{
  id: 'n18d', actId: 'act8', title: '录制', type: 'normal', order: 6,
  position: { x: 3500, y: 720 },
  emotionFunction: { emotionIn: '行动', emotionOut: '清澈', playerEmotion: '独自的公正', tension: 7 },
  systemFunction: { variablesRead: ['conviction'], variablesWrite: ['courage'], requirements: 'conviction>=8' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'NIGHT', interior: 'INT' },
  sceneDesc: '方静打开手机录音，独自开始录制。',
  dialogue: [
    dl('n18d',1,'','方静打开手机，找到录音软件，把手机放在桌上，对着它坐下来。','平静'),
    dl('n18d',2,'','她想了一下，按下了录音键。','平静'),
    dl('n18d',3,'方静','我是方静，退休法官，退休前在XX中级人民法院工作三十年。','平静'),
    dl('n18d',4,'方静','以下是我关于二十年前一个案件的陈述，陈国民故意杀人案，案件编号——','平静'),
    dl('n18d',5,'','她报出了案件编号，她记得，她一直记得。','专注'),
    dl('n18d',6,'方静','庭审第三天，证人陈福海出庭。他的证词，在我当年的工作笔记里，我有一条备注：「供述时间线：晚9:15—9:30空白，待查。」','平静'),
    dl('n18d',7,'方静','我没有追查这个问题。这是我的失职。我现在以退休法官的身份，陈述这一事实，并请求相关机构对本案进行复查。','平静'),
    dl('n18d',8,'','她停下来，喝了一口水，继续。','平静'),
    dl('n18d',9,'方静','我陈述的出发点不是为了开脱责任，也不是因为外部压力。我陈述的原因是：一个人在监狱里待了二十年，如果这是个错误，那么知道这件事的人就有责任说出来。','坚定'),
    dl('n18d',10,'方静','即使代价是我自己的名誉。即使这个陈述会让很多人不舒服，包括我。','坚定'),
    dl('n18d',11,'','她停下录音，把文件保存，准备发到三个地方：最高人民检察院申诉部门，陈晓晴，还有她的律师朋友范晖。','专注'),
    dl('n18d',12,'','她发完，把手机放下，在书房里坐着，听着夜里的安静。','平静'),
    dl('n18d',13,'','她想，这件事做完了，她可以睡一觉了。','平静'),
    dl('n18d',14,'','是很久以来第一次，她觉得可以。','释然'),
  ],
  choices: [ ch('n18d',1,'结局','n20d','','','light') ],
  durationSeconds: 172, notes: '', dramaticWeight: 'payoff',
},

// ── n20a ENDING good ──────────────────────────────────────────────────
{
  id: 'n20a', actId: 'act9', title: '迟到的公正', type: 'ending', order: 0,
  position: { x: 3900, y: 180 },
  emotionFunction: { emotionIn: '等待', emotionOut: '复杂的平静', playerEmotion: '迟来的释然', tension: 5 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '三个月后，法院门口，陈国民走出来了。方静在家里看直播。',
  dialogue: [
    dl('n20a',1,'','三个月后，一个普通的周三下午，方静在家看手机直播。','平静'),
    dl('n20a',2,'','陈晓晴的直播，法院门口，一个六十岁出头、头发全白的男人走出来，阳光里他先停了一下，闭上眼睛。','平静'),
    dl('n20a',3,'','陈晓晴没有采访他，只是跟着他走了几步，然后停下来，让他和家人见面。','平静'),
    dl('n20a',4,'','方静的手机响了，是她的儿子。','平静'),
    dl('n20a',5,'方静的儿子[电话]','妈，我看到新闻了。','平静'),
    dl('n20a',6,'方静','嗯。','平静'),
    dl('n20a',7,'方静的儿子[电话]','你还好吗？','关心'),
    dl('n20a',8,'方静','还好。','平静'),
    dl('n20a',9,'方静的儿子[电话]','那个……你写那个陈述，是需要勇气的。','低沉'),
    dl('n20a',10,'方静','[停顿] 不是勇气。是欠的，还一下。','平静'),
    dl('n20a',11,'','电话里沉默了一会儿。','沉默'),
    dl('n20a',12,'方静的儿子[电话]','妈，你当年……','平静'),
    dl('n20a',13,'方静','[轻轻地] 我知道你想问什么。以后有机会，我跟你说。','平静'),
    dl('n20a',14,'','她挂掉电话，把手机放下，屏幕上，陈国民在阳光里站着，他的女儿站在他旁边。','平静'),
    dl('n20a',15,'','方静看着这个画面，待了很久。','内心'),
    dl('n20a',16,'','迟到的，但是到了。','平静'),
  ],
  choices: [],
  durationSeconds: 250, notes: '', dramaticWeight: 'payoff',
},

// ── n20b ENDING neutral ────────────────────────────────────────────────
{
  id: 'n20b', actId: 'act9', title: '静默的代价', type: 'ending', order: 1,
  position: { x: 3900, y: 360 },
  emotionFunction: { emotionIn: '复杂', emotionOut: '悬而未决', playerEmotion: '无法定义', tension: 4 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家客厅', timeOfDay: 'AFTERNOON', interior: 'INT' },
  sceneDesc: '某个星期三的下午，陈国民走出来了，没有媒体，没有任何人知道为什么。',
  dialogue: [
    dl('n20b',1,'','陈晓晴给方静发了一条短信：「他今天出来了。谢谢您。」','平静'),
    dl('n20b',2,'','没有其他内容。方静回了一个字：「好。」','平静'),
    dl('n20b',3,'','那天下午，没有新闻，没有直播，什么都没有发生。','平静'),
    dl('n20b',4,'','陈国民在某个城市里，一个没有人知道他是谁的城市，开始了新的生活。','平静'),
    dl('n20b',5,'','一周后，方静收到了一封信，没有寄信人地址，邮戳是一个她不认识的城市。','平静'),
    dl('n20b',6,'','里面只有一张白纸，上面一行字：「谢谢这个不知道是谁的人。」','平静'),
    dl('n20b',7,'','方静把那张纸叠起来，放进书桌第一个抽屉里。','内心'),
    dl('n20b',8,'','没有公开，没有承认，没有道歉，没有判决的推翻。','内心'),
    dl('n20b',9,'','有的只是一个人出来了，还有这封没有名字的信。','内心'),
    dl('n20b',10,'','方静拿出那本旧笔记，翻到那一页，把那行「待查」划掉了，在旁边写了今天的日期。','平静'),
    dl('n20b',11,'','她不知道这算不算查了。','内心'),
    dl('n20b',12,'','但陈国民出来了，信在抽屉里，她可以告诉自己，某种意义上，结束了。','内心'),
    dl('n20b',13,'','她不确定这是不是她想要的结束。但这是她选择的那种结束。','内心'),
  ],
  choices: [],
  durationSeconds: 220, notes: '', dramaticWeight: 'relief',
},

// ── n20c ENDING bad ────────────────────────────────────────────────────
{
  id: 'n20c', actId: 'act9', title: '法庭上看到的', type: 'ending', order: 2,
  position: { x: 3900, y: 540 },
  emotionFunction: { emotionIn: '空洞', emotionOut: '遗憾', playerEmotion: '错过了', tension: 4 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '方静家书房', timeOfDay: 'AFTERNOON', interior: 'INT' },
  sceneDesc: '两年后，陈晓晴的报道在另一个地方重新引起关注。方静不在那个故事里了。',
  dialogue: [
    dl('n20c',1,'','两年后的某一天，方静在手机上刷到一条新闻。','平静'),
    dl('n20c',2,'','陈晓晴的那篇报道，在另一个媒体被重新引用，引发了关于司法错案的新一轮讨论。','平静'),
    dl('n20c',3,'','新的讨论里，有更多的案子，陈国民的只是其中一个被提到的。','平静'),
    dl('n20c',4,'','方静的名字不在里面，一次都没有被提到。','平静'),
    dl('n20c',5,'','她不是这个故事的一部分了。','内心'),
    dl('n20c',6,'','她打开书桌的抽屉，拿出那本旧笔记，翻到那一页。','专注'),
    dl('n20c',7,'','「待查。」','内心'),
    dl('n20c',8,'','两个字还在那里，和两年前一样，和二十年前一样。','内心'),
    dl('n20c',9,'','她把笔记合上，放回去，关上抽屉。','平静'),
    dl('n20c',10,'','窗外是正常的城市，正常的下午，一切如常。','空洞'),
    dl('n20c',11,'','方静坐在书房里，想起了陈晓晴那句话：「您的那本笔记里，有一行「待查」，那不是我写的，是您写的。」','回忆'),
    dl('n20c',12,'','是她写的。一直是。','内心'),
    dl('n20c',13,'','她不知道它会在那个抽屉里待多少年，她只知道，它还在。','内心'),
  ],
  choices: [],
  durationSeconds: 220, notes: '', dramaticWeight: 'relief',
},

// ── n20d ENDING secret ─────────────────────────────────────────────────
{
  id: 'n20d', actId: 'act9', title: '最后的陈述', type: 'ending', order: 3,
  position: { x: 3900, y: 720 },
  emotionFunction: { emotionIn: '清澈', emotionOut: '迟来的和解', playerEmotion: '见证', tension: 3 },
  systemFunction: { variablesRead: [], variablesWrite: [], requirements: '' },
  sceneHeader: { location: '某个公寓', timeOfDay: 'DAY', interior: 'INT' },
  sceneDesc: '方静去世后，她的儿子在整理遗物时发现了那份录像的副本。',
  dialogue: [
    dl('n20d',1,'','方静去世后，她的儿子来整理遗物。','平静'),
    dl('n20d',2,'','书房很整洁，像她这个人一样。书按照类别排好，文件分门别类，每一个抽屉里的东西都有标签。','平静'),
    dl('n20d',3,'','最下面的抽屉，一个信封，上面写着儿子的名字。','发现'),
    dl('n20d',4,'','信封里有一封信和一个U盘。','平静'),
    dl('n20d',5,'','信不长，写道：「这个U盘里有一段录像，是我在某年某月某日录制的，关于一个案件的陈述。那份陈述我已经发给了相关部门，这里留了一份副本。你不需要做任何事，只是我想让你知道，妈妈做了这件事。」','平静'),
    dl('n20d',6,'','方静的儿子把U盘插进电脑，看完了那段录像。','平静'),
    dl('n20d',7,'','「即使代价是我自己的名誉。」','回忆'),
    dl('n20d',8,'','他坐在那里，在母亲整洁的书房里，坐了很久。','内心'),
    dl('n20d',9,'','他给陈晓晴发了一条消息：「我是方静的儿子，我看到了那份录像，谢谢你当年去敲她的门。」','平静'),
    dl('n20d',10,'陈晓晴[消息]','谢谢她开了那扇门。','平静'),
    dl('n20d',11,'','方静的儿子看着书房窗外，阳光正好。','平静'),
    dl('n20d',12,'','他把那本旧笔记从桌上拿起来，翻到那一页，看到那行「待查」——旁边已经有了一个日期，是方静自己写上去的。','发现'),
    dl('n20d',13,'','是她查了。用她自己的方式，用她自己的时间，但她查了。','平静'),
  ],
  choices: [],
  durationSeconds: 260, notes: '', dramaticWeight: 'payoff',
},

]

// ── variables ─────────────────────────────────────────────────────────────
const variables = [
  { id: 'var_conviction', name: 'conviction', type: 'counter', defaultValue: '0', description: '方静对陈国民清白的认定程度（0-10）' },
  { id: 'var_courage', name: 'courage', type: 'flag', defaultValue: 'false', description: '方静是否决定主动行动' },
]

// ── endings ───────────────────────────────────────────────────────────────
const endings = [
  { id: 'end_good', nodeId: 'n20a', title: '迟到的公正', type: 'good', description: '方静公开陈述，陈国民案重审，他走出了法院门口。代价是方静的名誉，但她说"是欠的，还一下"。', conditions: 'conviction>=6 AND courage==true', variableConditions: [{variableName:'conviction',operator:'>=',value:6},{variableName:'courage',operator:'==',value:'true'}], requiredChoiceIds: [], reachPath: '打给晓晴或对抗林德福，最终选择公开陈述' },
  { id: 'end_neutral', nodeId: 'n20b', title: '静默的代价', type: 'neutral', description: '方静私下施压，陈国民假释出来，但案子没有公开平反。一封没有署名的信，说"谢谢不知道是谁的人"。', conditions: 'conviction>=4 AND courage==true', variableConditions: [{variableName:'conviction',operator:'>=',value:4}], requiredChoiceIds: [], reachPath: '发短信给林德福，选择私下施压' },
  { id: 'end_bad', nodeId: 'n20c', title: '法庭上看到的', type: 'bad', description: '方静拒绝承认，两年后陈晓晴的报道在别处引发讨论，但方静不在那个故事里了。那本笔记里的"待查"，还在。', conditions: '', variableConditions: [], requiredChoiceIds: [], reachPath: '选择拒绝，把文件夹放在门口' },
  { id: 'end_secret', nodeId: 'n20d', title: '最后的陈述', type: 'secret', description: '方静独自录制陈述寄给最高院，在儿子整理遗物时发现了副本。她用自己的方式，查了那两个字。', conditions: 'conviction>=8 AND courage==true', variableConditions: [{variableName:'conviction',operator:'>=',value:8},{variableName:'courage',operator:'==',value:'true'}], requiredChoiceIds: [], reachPath: '需要conviction≥8，选择"录制陈述"隐藏选项' },
]

// ── lastValidation ─────────────────────────────────────────────────────────
const lastValidation = {
  generatedAt: now,
  totalNodes: nodes.length,
  totalBranches: nodes.filter(n=>n.type==='branch').length,
  issues: [],
  passRate: 1.0,
}

// ── directorReview ─────────────────────────────────────────────────────────
const directorReview = {
  generatedAt: now,
  verdicts: [
    { lens: '道德张力', score: 9, observation: '核心困境极具份量：主角不是受害者，她是当年选择不追究的人。这比"被欺骗"的故事更难承受，也更真实。', note: '便条"待查"是绝佳的道具，始终在场。' },
    { lens: '角色真实性', score: 8, observation: '方静的克制与陈晓晴的偶尔失控形成有效对比。林德福不是坏人，只是一个相信"程序"的人，这让他更可怕。', note: '林德福的"那个"是全剧最好的台词之一。' },
    { lens: '互动设计', score: 8, observation: '5个分支点，每个分支有2-3个专属节点，玩家感受到选择的重量。隐藏结局的条件设计合理。', note: '建议在实现时确保变量条件正确传递。' },
    { lens: '节奏控制', score: 7, observation: '前两章节奏稳定，第三章最终决定前稍显平铺。EXPLORE节点有效提供了喘息空间。', note: '结局节点的质量参差，good结局最强，bad结局稍弱。' },
  ],
  overallScore: 8,
  greenlit: true,
  executiveSummary: '《证人席》是一个关于职业良知和个人勇气的互动叙事，核心困境扎实，角色有说服力，互动结构经过重新设计后显著改善。方静不是无辜的受害者而是"选择不追究"的人，这个设定赋予了故事真正的戏剧重量。推荐制作。',
  mustFix: [],
}

// ── scalePlan ──────────────────────────────────────────────────────────────
const scalePlanOptions = [{
  id: 'plan_ws_full',
  label: '标准版',
  chapterCount: 3,
  actCountPerChapter: 3,
  totalNodes: nodes.length,
  totalBranches: nodes.filter(n=>n.type==='branch').length,
  estimatedHours: 75,
  aiRationale: '三章分别对应「接触」「调查」「抉择」三个阶段，每章有三幕。五个分支点均有2-3个专属路径节点，确保玩家感受到选择的重量。',
  chapters: chapters.map(c=>({title:c.title, brief:''})),
}]

const project = {
  id: 'witness_stand',
  title: '证人席',
  createdAt: '2026-04-06T00:00:00.000Z',
  updatedAt: now,
  currentPhase: 'validate',
  phaseProgress: { world:'done', scale:'done', structure:'done', workshop:'done', validate:'done' },
  worldAnchor: {
    storyCore: '退休法官方静，深夜被年轻记者陈晓晴敲门。二十年前，方静主审的案件可能是冤案。但方静不是被欺骗的受害者——她当年在庭审笔记里写过「待查」，然后选择了不查。',
    theme: '职业良知与个人勇气——当你意识到自己可能造成了不可挽回的错误，你是选择正视还是防御？「铁面无私」的人，也可以有「差不多了」的念头。',
    genre: '法律悬疑 + 道德剧',
    worldRules: '1. 陈国民已在监狱待了二十年，案件当年在社会上影响很大，方静因此案得到嘉奖\n2. 当年的检察官林德福现在是副检察长，是方静的老朋友，也是最有可能压制此事的人\n3. 陈晓晴不只是记者，她是在没有父亲的家庭里长大的人——她不是来寻求同情的，她是来弄清楚的\n4. 案件中有一个细节方静当年注意到但没有追究：被告供述的时间线有15分钟的空白，方静在笔记里写了「待查」，然后就没有了然后',
    durationMinutes: 75,
    endingCount: 4,
    endingsDesign: endings.map(e=>({ id:e.id+'_design', title:e.title, type:e.type, description:e.description, triggerCondition:e.conditions, avoidCondition:'', keyVariable: e.type==='secret'?'conviction':'' })),
  },
  characters: [
    { id: 'c_fangjing', name: '方静', role: 'protagonist', motivation: '65岁，退休法官，三十年职业生涯，以"铁面无私"著称。外在克制、精准，内在承载着一个她不敢正视的问题。', relationship: '玩家的视角，她的挣扎就是玩家的挣扎', wound: '她以为自己三十年都做对了，而现在面对的是一个「差不多了」的念头改变了一个人一生的可能', lie: '告诉自己"程序正确就是公正"，但程序有时候是遮羞布', want: '维持她的自我认知，"我是一个好法官"', need: '承认自己是那个在关键时刻选择了不仔细的人', voiceProfile: { speaking_rhythm: '短句，精准，习惯反问', vocabulary: '职业化，不用情绪词描述情绪', defense_mechanism: '提问而不是陈述', lie_tells: '声音没有变化，但停顿变长了', sample_lines: ['我当时注意到了。我写了「待查」，然后案子走完了，我没有回去查。','「知道」和「能做什么」是两件事。','不用谢，这是我应该做的。二十年前就应该做的。'] } },
    { id: 'c_chenxiaoqing', name: '陈晓晴', role: 'antagonist', motivation: '28岁，调查记者，锐利，有三年的准备，偶尔控制不住的愤怒藏在职业外表下。', relationship: '她代表了所有因为「程序正确」而被碾碎的具体的人', wound: '在没有父亲的家庭里长大，父亲从来没有喊过冤，只说「我没有做」', lie: '告诉自己只要找到真相就好，但她也在审判那些让真相消失的人', want: '弄清楚真相，让父亲出来', need: '允许自己需要别人的承认，不只是法律的', voiceProfile: { speaking_rhythm: '有时克制，有时突然失控，用「我」而不是「我父亲」', vocabulary: '职业化的包装里有私人的伤', defense_mechanism: '用精确性来掩盖愤怒', lie_tells: '眼眶变红，但没有哭', sample_lines: ['我父亲进监狱那年，我十一岁。我妈带我去探视，他隔着玻璃问我期末考了多少分。','我不是来审判您的，我只是想让您知道，我知道那两个字在那里。','谢谢她开了那扇门。'] } },
    { id: 'c_lindefu', name: '林德福', role: 'antagonist', motivation: '62岁，现任副检察长，当年的检察官。不是坏人，是一个相信"程序"和"当时情况"的人。', relationship: '他保护方静，也是在保护自己。他的存在给了方静一个不行动的理由', wound: '职业生涯里见过太多"程序正确的错误"，学会了接受', lie: '告诉自己"当时的情况就是这样"，从不追问"情况为什么是那样"', want: '让这件事安静下去，保护相关的人包括自己', need: '承认他不是中立的，他的"保护"是有选择性的', voiceProfile: { speaking_rhythm: '圆滑，每句话两个意思，说完才让你反应', vocabulary: '用"咱们"，用"当时的情况"，从不说"我做了"', defense_mechanism: '把责任稀释进程序和集体', lie_tells: '停顿，然后转移话题', sample_lines: ['咱们认识三十年了，我就是来看看你。','有些事情当时的情况是那样的。','静姐，有些事情翻出来不会只影响陈国民这一个案子。'] } },
  ],
  selectedScalePlanId: 'plan_ws_full',
  scalePlanOptions,
  chapters,
  acts,
  nodes,
  variables,
  endings,
  lastValidation,
  directorReview,
  downstreamStale: false,
  schemaVersion: 1,
}

const outPath = join(__dirname, '../data/projects/witness_stand.json')
writeFileSync(outPath, JSON.stringify(project, null, 2), 'utf8')
console.log('Written:', outPath)
console.log('Nodes:', nodes.length, '| Branches:', nodes.filter(n=>n.type==='branch').length)
const totalSecs = nodes.reduce((s,n)=>s+(n.durationSeconds||0),0)
console.log('Total duration:', Math.round(totalSecs/60), 'min')
const avgDial = nodes.reduce((s,n)=>s+n.dialogue.length,0)/nodes.length
console.log('Avg dialogue:', avgDial.toFixed(1), 'lines/node')
// check links
const nodeIds = new Set(nodes.map(n=>n.id))
let broken=0
nodes.forEach(n=>n.choices.forEach(c=>{ if(c.targetNodeId && !nodeIds.has(c.targetNodeId)){ console.log('BROKEN:',n.id,'->',c.targetNodeId); broken++ } }))
console.log('Broken links:', broken)
